# Generated by Django 5.2.5 on 2025-08-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='number_eligible',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='number_screened',
        ),
    ]
