# Generated by Django 5.2.5 on 2025-08-09 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='date_sent',
            new_name='sent_at',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='monitor_download_date',
            new_name='monitor_downloaded_at',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='ultrasound_download_date',
            new_name='ultrasound_downloaded_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ultrasound_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='location',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='participant',
            name='monitor_downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='ultrasound_downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultrasound_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RA', 'Research Assistant'), ('RO', 'Research Officer'), ('AD', 'Administrator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.site'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('DAILY_PROMPT', 'Daily Prompt'), ('EARLY_REMINDER', 'Early Reminder'), ('FINAL_REMINDER', 'Final Reminder'), ('OVERDUE_ALERT', 'Overdue Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participant',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.site'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='study_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
