# Generated by Django 5.2.5 on 2025-08-24 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_participant_number_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
