# Generated by Django 5.2.5 on 2025-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='admission_notes_24hr_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='admission_notes_day1_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='blood_culture_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='blood_culture_result_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='case_report_form_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='cost_effectiveness_data_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='head_ultrasound_images_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='head_ultrasound_report_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_tracking_log_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='rop_final_report_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='rop_screening_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='video_laryngoscope_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='vital_sign_monitoring_done',
            field=models.BooleanField(default=False),
        ),
    ]
