# Generated by Django 5.2.5 on 2025-08-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_participant_admission_notes_24hr_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='blood_culture_done',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_tracking_log_uploaded',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='rop_screening_done',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ultrasound_done',
        ),
    ]
