# Generated by Django 5.2.5 on 2025-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_rename_blood_culture_result_uploaded_participant_blood_culture_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='monitor_downloaded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='ultrasound_downloaded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
